### ISSUE TITLE
Erro OKGER23

### ISSUE THREAD

**Issue by Richsan** [Richsan/Krakacomp#3]
no OKGER23 linha 24 temos uma declaração assign:
int i = 0;

a gente não tá considerando isso na implementação até então, o localdec só reconhece declaraçoes com virgula (ex: int a,b,c;) E o assignExpr só reconhece assignment sem declaração.
Vai ter que bolar alguma estratégia no aeld ou no localdec pra identificar se na hora da declaração há um assign, não tem testes para tal mas talvez possa ter declarações com mais de 1 assignment (ex: int a = 0, b = 1;)
Uma ideia  que me surgiu agora é chamar o aeld na localdec toda vez que ver um ident talvez.

**Comment by guilhermejcgois** [comment]
Acho melhor no localdec, porquê já vamos estar analisando isso, acho que vamos precisar de um tipo com um valor "_default_", ou simplesmente adicionamos um campo no tipo que já temos, se não for uma declaração com _assign_ inferimos o valor padrão (temos/sabemos esses valores _default_?)
