### ISSUE TITLE
Incremento e Decremento

### ISSUE THREAD

**Issue by Richsan** [Richsan/Krakacomp#4]
Não vi nenhum erro de teste até agora em relação a incremento e decremento com a implementação que foi feita dele como statement, só não conferi na parte semantica.
Mas parece que tá funcionando desse jeito, acho que dá pra deixar assim, apesar de eu achar que ele deveria ser um expr.
Talvez traga problema nos testes de geração de codigo, mas creio que não vai trazer não, então acho que dá pra deixar assim e se surgir algum problema temos essa issue aqui pra lembrar desse ponto.

**Comment by guilhermejcgois** [comment]
Trouxe problema na geração de código sim hahaha

Mas já resolvi ;)
