### ISSUE TITLE
O que fazer agora?

### ISSUE THREAD

**Issue by Richsan** [Richsan/Krakacomp#5]
- [x]  Corrigir NullPointerException desta [issue](https://github.com/Richsan/Krakacomp/issues/6)
- [x] Corrigir erro da issue [ErroOKGER23](https://github.com/Richsan/Krakacomp/issues/3)
- [x] Implementar todos genKra das classes da AST
- [x] Corrigir todos os erros semânticos informados pelo[ relatorio](https://github.com/Richsan/Krakacomp/blob/master/krakatoa/report-sem.txt).
- [x] Verificar se a geração de codigo do genKra ta correta
- [x] Entregar e ser feliz.
- [x] Abrir uma breja gelada e comemorar (y)

**Comment by guilhermejcgois** [comment]
Fechei essa sem querer no commit e tinha deixado outras abertas que eram pra fechar rs

**Comment by guilhermejcgois** [comment]
Ver o que mais precisa fazer pra entregar (RAs, etc.)
